grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 2
model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: 0.1
      max_features: 5
      min_samples_split: 2
      n_estimators: 100
    search_param_grid:
      min_samples_split:
      - 2
      - 8
      - 15
      max_features:
      - 5
      - "sqrt"
      - "log2"
      n_estimators:
      - 100
      - 200
      - 1000
      max_depth:
      - 5
      - 8
      - 10
  module_1:
    class : XGBRegressor
    module : xgboost
    params:
      booster: bgtree
      verbosity : 1
      nthreads : 100
      max_depth: 0.1
      learning_rate: 0.05
      min_child_weight: 1
      n_estimators: 100
    
    search_param_grid:
      booster:
      - gbtree
      - gblinear
      - dart
      verbosity : 
      - 1
      - 2
      - 3
      - 4
      nthreads :
      - 10
      - 100
      - 1000
      
      n_estimators:
      - 100
      - 200
      - 1000
      max_depth:
      - 5
      - 8
      - 10

      learning_rate:
      - 0.05
      - 0.1 
      - 0.15
      - 0.20
      min_child_weight:
      - 1
      - 2
      - 3
      - 4